export const CREATE_CONTACT="CREATE_CONTACT"
export const GET_CONTACT="GET_CONTACT"
export const UPDATE_CONTACT="UPDATE_CONTACT"
export const DELETE_CONTACT="DELETE_CONTACT"
// filtering
export const FILTER_CONTACT="FILTER_CONTACT"
